version: '3'

services:
  postgres:
    image: postgres:12-alpine
    container_name: prettychat
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: prettychat
      POSTGRES_DB: prettychat


